### ISSUE TITLE
Predefined value on Custom Content Type

### ISSUE THREAD

**Issue by hawjeh** [Sitefinity/sitefinity-admin-app-extensions#163]
Is there a way to extend admin app and set predefined value in the custom content type Short Text / Long Text fields?
Found a way to do it in legacy UI but it does not for the new adminapp UI.
Legacy UI: https://www.progress.com/blogs/how-to-add-predefined-values-to-the-backend-create-view-of-dynamic-content-items

**Comment by annix8** [comment]
Hi,

Currently, there are 2 ways to achieve this and the answers are found in our custom-fields extensions examples [here](https://github.com/Sitefinity/sitefinity-admin-app-extensions/tree/master/custom-fields).

The first approach is to go to the custom-fields.settings.ts and write these lines in the init() function: this["defaultValue"] = "Your desired default value"; and this["markAsDirty"] = true; . This will set the value for the custom field you are overriding and mark it as dirty so you can publish directly passing the validation for empty field value.

The second approach would be to go to the custom-field-write.component and override the writeValue function in the following way:
writeValue(value) {
        if (!value) {
            setTimeout(() => {
                super.writeValue("Your desired default value");
            }, 500);

            return;
        }

        super.writeValue(value);
    }
The setTimeout is required because if you call the super.writeValue without the default implementation of the writeValue will be called right after yours and will override your changes.

Regards
