### ISSUE TITLE
Old dependence - @angular/http

### ISSUE THREAD

**Issue by AxGord** [Sitefinity/sitefinity-admin-app-extensions#289]
```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"7.2.15" from @angular/http@7.2.15
npm ERR! node_modules/@angular/http
npm ERR! peer @angular/http@"<=7.2.15" from progress-sitefinity-adminapp-sdk@13.2.7524
```

**Comment by Novkirishki** [comment]
Hi @AxGord, thank you for reporting this. 

I tried to reproduce the issue with tag [13.2.7524.0](https://github.com/Sitefinity/sitefinity-admin-app-extensions/releases/tag/13.2.7524.0), but couldn't. Everything seemed to work as expected, no npm errors on install, no errors on start. 

What node and npm versions are you using? Can you try upgrading to latest and check whether the issue persists? 

Regards

**Comment by AxGord** [comment]
```sh
node -v
v14.16.0
npm -v
7.6.0
```
`npm i` - error
`npm i --legacy-peer-deps` - working

**Comment by Novkirishki** [comment]
Hi @AxGord, 
I tried to reproduce the issue with the exact same version that you use, but everything worked OK on my end. 

However I notised that a lot of changes were applied to the **package-lock.json** file. This is because it was generated with npm v6 and doing `npm i` with a higher version of npm regenerates the file. It is expected that previous tags of the repository contain files generated with older npm versions.

As you have noted one of the solutions is to use the **legacy-peer-deps** flag. Another solutions is to delete the **package-lock.json** file and do `npm i` again.

Best regards

**Comment by AxGord** [comment]
There is a problem even if remove the package-lock.json and node_modules.
This works if take package-lock.json from the repository.
But as I understand it, this means that there is a problem.
In my repository, package-lock.json is added to .gitignore and after cloning it, additional actions are required. It is sad.

**Comment by Novkirishki** [comment]
Hi @AxGord, 

you should not delete the package-json.file that comes from our repository. The file is needed so that you can recreate the exact same packages tree on your end as we have on our machines. The reason you get the error is because you are using a new version of npm and you delete the package-lock.json file. The npm documentation states: 

> This file is intended to be committed into source repositories

I previously suggested to delete the file because I thought the problem may be coming from it, but now I understand that you are deleting it before even doing `npm i`.

Hope this helps.
