### ISSUE TITLE
Dynamic content selector in the content editor

### ISSUE THREAD

**Issue by YavorSlavchev** [Sitefinity/sitefinity-admin-app-extensions#295]
Hi,
I want to add a new toolbar button that opens a dynamic content selector from specified type and select an item that needs to be processed afterwards.
Currently, the SelectorService supports only Image and Video library selector. I see there is an additional openDialog method but I cannot find any API documentation of how to use it.
So what is the recommended way of adding a dynamic content selector in the editor toolbar?

**Comment by annix8** [comment]
Hi,

Before implementing custom dialogs, have you seen the insert link button and functionality and do you think it could serve your purpose? It also opens a dialog and lets you select the type of content item you would like to link in the editor. If you do not think this handles your scenario, the way I can suggest using the openDialog function is the following:
 - You create your own component that will be visualized in the dialog and will take care of things like retrieving the dynamic items from the server and visualizing them in the HTML, selecting and deselcting etc.
 - After that you will need to build the DialogData object in order to call the openDialog function of the selectorService. And example would be:
```
 const dialogData: DialogData = {
                    componentData: {
                        type: MyCustomComponent
                    },
                    commands: [{
                        name: "Cancel",
                        title: "Cancel",
                        ordinal: -1,
                        category: "cancel"
                    },
                    {
                        name: "Confirm",
                        title: "Confirm",
                        ordinal: -1,
                        category: "primary"
                    }]
                };
```
where these commands are the buttons that will be shown at the bottom of the dialog and MyCustomComponent is your newly created component with the logic I mentioned above.
- You can then call the openDialog function passing this dialogData to it and subscribe to the result. The result will be an object containing your custom component as a property from which you can access the selected items and then work on them however you like

Here (https://github.com/Sitefinity/sitefinity-admin-app-extensions/blob/master/src/commands-extender/print-preview.component.ts) you can find an example of how items are retrieved from the server. Basically, if you want to get newsitems, an example url would be `${HTTP_PREFIX}/sf/system/newsitems`

And don't forget to add your component to the declarations array in your extensions module :)

Regards

**Comment by YavorSlavchev** [comment]
Hi Mario,
Thanks for your response.
This basically means that I have to create the selector on my own. I cannot use the insert link button, as it is more complex and I just need to focus on one particular content type. Also, I need to insert my own custom attribute, similar to the sfref but do my own  processing of it.
One more question related to the example with retrieving data from the server. Isn't it necessary to authenticate using a token when calling the built-in, system odata services?
Thanks in advance.

**Comment by annix8** [comment]
Hi, Yavor,

You do not need to authenticate using a token as long as you use the HTTP_PREFIX constant when calling the OData services. Your request will be intercepted and you will be authenticated to call the endpoint

Regards

**Comment by YavorSlavchev** [comment]
Oh, that is lovely. Will give it a try. Thanks for the directions, Mario. Appreciate it. Closing this for now.
