### ISSUE TITLE
filtration on master detail related data in module builder to extend

### ISSUE THREAD

**Issue by shreeramghatwai** [Sitefinity/sitefinity-admin-app-extensions#384]
Hi,

We have a scenario where after selecting master data , automatically detail related data should get filter in sitefinity backend screen of module builder. can this be achieved or have achieved in past.. here is the example below , so classification code is selected as 'EX', after selection automatically dealer list should show only those dealers which are of 'EX' and not all dealers.

![image](https://user-images.githubusercontent.com/95875758/145446317-642608e7-fd2e-4ad9-9ec0-19ffa2551f16.png)
 
Thanks

**Comment by stefankoserkov** [comment]
Hello @shreeramghatwai,

Thank you for contacting us, and please excuse us for the delayed response.

The behavior that you are describing is not something that exists out-of-the-box in Sitefinity CMS, and in the AdminApp extensions. As such I encourage you to submit a feature request, please see this [KB article](https://knowledgebase.progress.com/articles/Knowledge/How-to-submit-a-Sitefinity-feature-request) for more information on how to do so.

For context, this is currently not possible in the AdminApp, because the angular components necessary to achieve what you have described are not exposed. However, if you were to implement, from scratch, a custom angular component that would fulfill your specific use-case, you can re-bind it with our [Custom fields extension](https://github.com/Sitefinity/sitefinity-admin-app-extensions/tree/master/src/custom-fields#custom-field).

If you have any further questions, please submit a [support case](https://www.progress.com/support/sitefinity-log-support-case).

Best regards,
Stefan
